import { useEffect, useRef } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import lottie from "lottie-web";

export default function Home() {
  const container = useRef(null);

  useEffect(() => {
    lottie.loadAnimation({
      container: container.current,
      renderer: "canvas",
      loop: true,
      autoplay: true,
      animationData: require("../assets/anim_data.json"),
    });
    return () => {
      lottie.destroy();
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Lottie File Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.text}>
        <h1>This is a Lottie Files test page</h1>
        <p className={styles.paragraph}>
          I discovered lottie a while back and fell in love with it because well
          I just love motion. <br />
          Today, I decided to test it out with Next Js and it works like a
          charm. Will surely use this in the future for my projects!{" "}
        </p>
      </div>
      <div className={styles.anim_container} ref={container}></div>
    </div>
  );
}
